#!/usr/bin/env bash
set -euo pipefail

# Sync GitHub issues into the local .ai/issues directory for development context.
#
# Examples:
#   ./scripts/sync-github-issues-to-ai.sh --repo ihandley/coach --label job-coach-rebuild
#   ./scripts/sync-github-issues-to-ai.sh --repo ihandley/coach --issue 123
#   ./scripts/sync-github-issues-to-ai.sh --repo ihandley/coach --issue 123 --issue 124
#   ./scripts/sync-github-issues-to-ai.sh --repo ihandley/coach --state all --limit 50
#
# Notes:
# - This script is developer tooling only.
# - It is not part of the product runtime.
# - It may be used during migration and planning work, but the canonical product
#   behavior lives in the application code, persistence layer, workflows, and docs
#   in this repository.

REPO=""
STATE="open"
LIMIT="100"
LABEL=""
OUT_DIR=".ai/issues"

declare -a ISSUE_IDS=()

usage() {
  cat <<'EOF'
Usage:
  ./scripts/sync-github-issues-to-ai.sh --repo <owner/repo> [options]

Options:
  --repo <owner/repo>     GitHub repository, for example ihandley/coach
  --issue <number>        Sync a specific issue number (repeatable)
  --state <state>         open | closed | all (default: open)
  --label <label>         Filter by label
  --limit <n>             Max issues to fetch when not using --issue (default: 100)
  --out <dir>             Output directory (default: .ai/issues)
  -h, --help              Show help
EOF
}

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

pad_issue() {
  printf '%04d' "$1"
}

write_index() {
  local index_file="$OUT_DIR/INDEX.md"
  {
    echo "# Synced GitHub Issues"
    echo
    echo "Generated by \`scripts/sync-github-issues-to-ai.sh\`."
    echo
    find "$OUT_DIR" -maxdepth 1 -type f -name '*.md' ! -name 'INDEX.md' | sort | while read -r file; do
      local base
      base="$(basename "$file")"
      echo "- [$base](./$base)"
    done
  } > "$index_file"
}

write_issue_file() {
  local number="$1"
  local title="$2"
  local state="$3"
  local labels="$4"
  local url="$5"
  local created_at="$6"
  local updated_at="$7"
  local body="$8"

  local slug
  slug="$(slugify "$title")"
  local padded
  padded="$(pad_issue "$number")"
  local file="$OUT_DIR/${padded}-${slug}.md"

  {
    echo "# GitHub Issue #$number"
    echo
    echo "- Title: $title"
    echo "- State: ${state^^}"
    echo "- Labels: $labels"
    echo "- URL: $url"
    echo "- Created: $created_at"
    echo "- Updated: $updated_at"
    echo
    echo "## Body"
    echo
    printf '%s\n' "$body"
  } > "$file"

  echo "Wrote $file"
}

fetch_single_issue() {
  local issue_id="$1"

  gh issue view "$issue_id" \
    --repo "$REPO" \
    --json number,title,state,labels,url,createdAt,updatedAt,body \
    --jq '[
      .number,
      .title,
      .state,
      (.labels | map(.name) | join(", ")),
      .url,
      .createdAt,
      .updatedAt,
      .body
    ] | @tsv'
}

fetch_issue_list() {
  local jq_filter='
    .[]
    | [
        .number,
        .title,
        .state,
        (.labels | map(.name) | join(", ")),
        .url,
        .createdAt,
        .updatedAt,
        .body
      ]
    | @tsv
  '

  if [[ -n "$LABEL" ]]; then
    gh issue list \
      --repo "$REPO" \
      --state "$STATE" \
      --limit "$LIMIT" \
      --label "$LABEL" \
      --json number,title,state,labels,url,createdAt,updatedAt,body \
      --jq "$jq_filter"
  else
    gh issue list \
      --repo "$REPO" \
      --state "$STATE" \
      --limit "$LIMIT" \
      --json number,title,state,labels,url,createdAt,updatedAt,body \
      --jq "$jq_filter"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      REPO="${2:-}"
      shift 2
      ;;
    --issue)
      ISSUE_IDS+=("${2:-}")
      shift 2
      ;;
    --state)
      STATE="${2:-}"
      shift 2
      ;;
    --label)
      LABEL="${2:-}"
      shift 2
      ;;
    --limit)
      LIMIT="${2:-}"
      shift 2
      ;;
    --out)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$REPO" ]]; then
  echo "Error: --repo is required" >&2
  usage
  exit 1
fi

mkdir -p "$OUT_DIR"

if [[ "${#ISSUE_IDS[@]}" -gt 0 ]]; then
  for issue_id in "${ISSUE_IDS[@]}"; do
    line="$(fetch_single_issue "$issue_id")"
    IFS=$'\t' read -r number title state labels url created_at updated_at body <<< "$line"
    write_issue_file "$number" "$title" "$state" "$labels" "$url" "$created_at" "$updated_at" "$body"
  done
else
  while IFS=$'\t' read -r number title state labels url created_at updated_at body; do
    [[ -z "${number:-}" ]] && continue
    write_issue_file "$number" "$title" "$state" "$labels" "$url" "$created_at" "$updated_at" "$body"
  done < <(fetch_issue_list)
fi

write_index
echo "Done."